ImageGuessingGame/Pages/Lobby/CreateGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ImageGuessingGame.GameContext.GameHandling;
using ImageGuessingGame.GameContext.SuggestionHandling;
using ImageGuessingGame.GameContext;

namespace ImageGuessingGame.Pages
{
    public class CreateGameModel : PageModel
    {
        private readonly ILoginUserProvider _loginUserProvider;
        private readonly IGameProvider _gameProvider;
        private readonly ISuggestionProvider _suggestionProvider;
        [BindProperty]
        public ICollection<LoginUser> LoginUsers{get;set;}
        public string LoggedUser;
        public string Error;

        public CreateGameModel(ILoginUserProvider loginProvider,IGameProvider gameProvider
                                ,ISuggestionProvider suggestionProvider)
        {
            _loginUserProvider = loginProvider;
            _gameProvider = gameProvider;
            _suggestionProvider = suggestionProvider;
        }

        public ActionResult OnGet()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            return Page();
        }
        public async Task<ActionResult> OnPostAsync()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            else{
                Error="You need to be logged in";
                return Page();
            }
            var user = await _loginUserProvider.GetLoginUserByName(LoggedUser);
            var gamemode = Request.Form["gamemode"].ToString();
            Game game;
            if (gamemode == "0"){
                game = new SinglePlayerGame(user);
            }else{
                game = new MultiPlayerGame(user);
            }
            await _gameProvider.AddGame(game);
            HttpContext.Session.SetString("GameGuid", game.Id.ToString());
            var suggestion = await _suggestionProvider.GetSuggestionForImage(game.Oracle.ImagePath);
            if (suggestion != null)
            {
                game.Oracle.Suggestion = suggestion;
                await _gameProvider.UpdateGame(game);
            }
            if (Int32.Parse(gamemode) == 1)
            {
                return RedirectToPage("./JoinMultiplayer", new { userName = user.UserName });
            }
            
            return RedirectToPage("./Game");
        }
    }

}

ImageGuessingGame/Pages/Lobby/Game.cshtml.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ImageGuessingGame.GameContext;
using ImageGuessingGame.GameContext.GameHandling;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageGuessingGame.Pages
{
    public class GameModel : PageModel
    {

        private readonly ILoginUserProvider _loginUserProvider;
        private readonly GuessingGameContext _guessingGameContext;
        private readonly IGameProvider _gameProvider;
        private readonly IGuessValidator _guessValidator;
        public string LoggedUser;
        public string Label;
        public string Guess;
        public string Success;


        public GameModel(ILoginUserProvider loginProvider, IGameProvider gameProvider
                            , GuessingGameContext guessingGameContext, IGuessValidator guessValidator)
        {
            _loginUserProvider = loginProvider;
            _gameProvider = gameProvider;
            _guessingGameContext = guessingGameContext;
            _guessValidator = guessValidator;
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {

            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            var user = await _loginUserProvider.GetLoginUserByName(LoggedUser);
            var guid = HttpContext.Session.GetString("GameGuid");
            var game = await _gameProvider.GetGameByGuid(Guid.Parse(guid));
            var gameplay = new Gameplay(game.Id);
            Label = game.Oracle.Label;
            Guess = Request.Form["Guess"];
            Console.WriteLine(Label);
            if (Request.Form["Guess"] != "")
            {
                if (_guessValidator.isCorrect(Label, Guess))
                {
                    Success = "Success you won";
                    var score = game.Oracle.PartialIndex.Count;
                    if (user.Highscore == 0)
                    {
                        user.Highscore = score;
                    }
                    else
                    {
                        if (score < user.Highscore)
                        {
                            user.Highscore = score;
                        }
                    }
                    game.Finished = true;
                    game.Score = score;
                    await _gameProvider.UpdateGame(game);
                    await _loginUserProvider.UpdateLoginUser(user);
                    return RedirectToPage("./Win");

                }
                else
                {
                    game.IncorrectCount++;
                    if (game.IncorrectCount >= 3)
                    {
                        game.Oracle.SelectTile();
                        game.IncorrectCount = 0;
                    }
                    await _gameProvider.UpdateGame(game);
                }
            }
            else
            {
                game.Oracle.SelectTile();
                await _gameProvider.UpdateGame(game);
            }

            return Page();
        }
        public async Task<IActionResult> OnPostQuitAsync()
        {
            var guid = HttpContext.Session.GetString("GameGuid");
            var game = await _gameProvider.GetGameByGuid(Guid.Parse(guid));
            game.Finished=true;
            return RedirectToPage("Lose");
        }
    }

}

ImageGuessingGame/Pages/Lobby/JoinMultiplayer.cshtml.cs
using System.Security.Cryptography;
using System.Net.Http;
using System.Net;
using System.Net.Cache;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ImageGuessingGame.GameContext;
using ImageGuessingGame.GameContext.GameHandling;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageGuessingGame.Pages
{
    public class JoinMultiplayerModel : PageModel
    {

        private readonly ILoginUserProvider _loginUserProvider;
        private readonly IGameProvider _gameProvider;
        public LoginUser LoggedUser;
        public bool IsCreator = false;
        public Game Game;


        public JoinMultiplayerModel(ILoginUserProvider loginProvider, IGameProvider gameProvider)
        {
            _loginUserProvider = loginProvider;
            _gameProvider = gameProvider;
        }

        public async Task<IActionResult> OnGet()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                var userName = HttpContext.Session.GetString("_Name");
                LoggedUser = await _loginUserProvider.GetLoginUserByName(userName);
                Guid gameId;
                try
                {
                    gameId = Guid.Parse(Request.Query["gameId"]);
                }
                catch
                {
                    gameId = Guid.Parse(HttpContext.Session.GetString("GameGuid"));
                }
                Game = await _gameProvider.GetGameByGuid(gameId);
                if (Game == null)
                {
                    return RedirectToPage("../Index");
                }

                if (!Game.MultiplayerOpenLobby)
                {
                    return RedirectToPage("../Index");
                }

                if (Game.Guesser.User == LoggedUser)
                {
                    IsCreator = true;
                }else{
                    HttpContext.Session.SetString("GameGuid", gameId.ToString());
                }

                return Page();
            }
            return RedirectToPage("../Index");
        }
    }

}

ImageGuessingGame/Pages/Lobby/Lobby.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ImageGuessingGame.GameContext.GameHandling;
using ImageGuessingGame.GameContext;



namespace ImageGuessingGame.Pages
{
    public class LobbyModel : PageModel
    {
        private readonly ILoginUserProvider _loginUserProvider;
        [BindProperty]
        public ICollection<LoginUser> LoginUsers { get; set; }
        private readonly IGameProvider _gameProvider;
        public string LoggedUser;
        public List<Game> Games { get; set; } = new();


        public LobbyModel(ILoginUserProvider Provider, IGameProvider gameProvider)
        {
            _loginUserProvider = Provider;
            _gameProvider = gameProvider;

        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            LoginUsers = await _loginUserProvider.GetLoginUsers();
            if (LoginUsers == null)
            {
                return NotFound();
            }
            var guid = HttpContext.Session.GetString("GameGuid");
            var game = await _gameProvider.GetGames();
            Games = game.Where(g=>g.Finished).OrderByDescending(g => g.TimeStarted).Take(5).ToList();
            return Page();
        }
    }
}

ImageGuessingGame/Pages/Lobby/Lose.cshtml.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ImageGuessingGame.GameContext;
using ImageGuessingGame.GameContext.GameHandling;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageGuessingGame.Pages
{
    public class LoseModel : PageModel
    {

        private readonly ILoginUserProvider _loginUserProvider;
        private readonly IGameProvider _gameProvider;
        public ICollection<string> ImageSlices;
        public string LoggedUser;
        public string Label{get;set;}
        public int Score{get;set;}



        public LoseModel(ILoginUserProvider loginProvider, IGameProvider gameProvider)
        {
            _loginUserProvider = loginProvider;
            _gameProvider = gameProvider;
        }

        public async Task<ActionResult> OnGet()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            var guid = HttpContext.Session.GetString("GameGuid");
            var game = await _gameProvider.GetGameByGuid(Guid.Parse(guid));
            game.Oracle.ImageProcessor.ShowFullImage(game.Oracle.ImagePath);
            Label = game.Oracle.Label;
            await _gameProvider.UpdateGame(game); 
            return Page();
        }
    }

}

ImageGuessingGame/Pages/Lobby/MultiplayerGame.cshtml.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ImageGuessingGame.GameContext;
using ImageGuessingGame.GameContext.GameHandling;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageGuessingGame.Pages
{
    public class MultiplayerGameModel : PageModel
    {

        private readonly ILoginUserProvider _loginUserProvider;
        private readonly GuessingGameContext _guessingGameContext;
        private readonly IGameProvider _gameProvider;
        private readonly IGuessValidator _guessValidator;
        public ICollection<string> ImageSlices;
        public string LoggedUser;
        public Game Game { get; set; }


        public MultiplayerGameModel(ILoginUserProvider loginProvider, IGameProvider gameProvider
                            , GuessingGameContext guessingGameContext, IGuessValidator guessValidator)
        {
            _loginUserProvider = loginProvider;
            _gameProvider = gameProvider;
            _guessingGameContext = guessingGameContext;
            _guessValidator = guessValidator;
        }

        public async  Task<IActionResult> OnGetAsync()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            else
            {
                return RedirectToPage("../Index");
            }
            try
            {
                var gameId = Guid.Parse(Request.Query["gameId"]);
                Game = await _gameProvider.GetGameByGuid(gameId);
            }
            catch
            {
                var gameId = Guid.Parse(HttpContext.Session.GetString("GameGuid"));
                Game = await _gameProvider.GetGameByGuid(gameId);
            }
            return Page();
        }
    }

}

ImageGuessingGame/Pages/Lobby/Suggest.cshtml.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ImageGuessingGame.GameContext;
using ImageGuessingGame.GameContext.GameHandling;
using ImageGuessingGame.GameContext.SuggestionHandling;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageGuessingGame.Pages
{
    public class SuggestModel : PageModel
    {

        private readonly ILoginUserProvider _loginUserProvider;
        private readonly IGameProvider _gameProvider;
        private readonly ISuggestionProvider _suggestionProvider;
        public string LoggedUser;
        public int Index;
        public SuggestModel(ILoginUserProvider loginProvider, IGameProvider gameProvider
                            , ISuggestionProvider suggestionProvider)
        {
            _loginUserProvider = loginProvider;
            _gameProvider = gameProvider;
            _suggestionProvider = suggestionProvider;
        }

        public async Task<ActionResult> OnGet()
        {
            if (HttpContext.Session.GetString("_Name") != null)
            {
                LoggedUser = HttpContext.Session.GetString("_Name");
            }
            var guid = HttpContext.Session.GetString("GameGuid");
            var game = await _gameProvider.GetGameByGuid(Guid.Parse(guid));
            var imageProcessor = new ImageProcessor();
            imageProcessor.ShowFullImage(game.Oracle.ImagePath);
            Index = -1;
            return Page();
        }
        public async Task<IActionResult> OnPostChooseAsync(string cursorx, string cursory){
            var guid = HttpContext.Session.GetString("GameGuid");
            var game = await _gameProvider.GetGameByGuid(Guid.Parse(guid));
            var xCor = Int32.Parse(cursorx);
            var yCor = Int32.Parse(cursory);
            var imagepath = game.Oracle.ImagePath;
            var imageProcessor = new ImageProcessor();
            int index_to_suggest  = imageProcessor.Find_slice_index(imagepath, xCor, yCor);
            GameContext.IndexSuggestion index = new GameContext.IndexSuggestion(index_to_suggest);
            if (await _suggestionProvider.GetSuggestionByGuid(Guid.Parse(guid)) == null) // First suggestion creates the list
            {
                var suggestion = new Suggestion(Guid.Parse(guid), imagepath);
                suggestion.IndexList = new List<GameContext.IndexSuggestion>();
                suggestion.IndexList.Add(index);
                await _suggestionProvider.AddSuggestions(suggestion);
            }
            else{ // adds more indexes to the list
                var suggestion = await _suggestionProvider.GetSuggestionByGuid(Guid.Parse(guid));
                suggestion.IndexList.Add(index);
                await _suggestionProvider.UpdateSuggestion(suggestion);
                if (suggestion.IndexList.Count >= 5){ // You only get to give 5 suggestions
                    return Redirect("Suggestions");
                }
            }
            Index=index.index;
            return Page();
        }
    }

}

ImageGuessingGame/Pages/Lobby/CreateGame.cshtml
@page
@model CreateGameModel
@{
    ViewData["Title"] = "CreateGame";
    string[] TableHeaders = new string[] {};
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
    }
}
<p>@Model.Error</p>
<form method="post">
    <label for="gamemode">Choose a gamemode:</label>
    <select name="gamemode" id="gamemode">
        <option value="0">Normal</option>
        <option value="1">Multiplayer</option>
    </select>
    <input type="submit" id="createGame" />
</form>
<br>
<form method=" " asp-page="./JoinMultiplayer">
    <h3>Join multiplayer game</h3>
    <label for="gameId">Enter Game ID</label>
    <input name="gameId" id="gameId" />
    <button type="submit" id="joinButton">Join</button>
</form>

<script>
    document
        .getElementById("joinButton")
        .addEventListener("click", function (event) {
            var gameId = document.getElementById("gameId").value;
            if (gameId != "") {
                const url = new URL("https://localhost:5001/JoinMultiplayer?gameId=" + gameId);
                window.location.replace(url);
            }
        });
</script>

ImageGuessingGame/Pages/Lobby/Game.cshtml
@page
@model GameModel
@{
    ViewData["Title"] = "Game";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<img src="../output.png" />


<form method="POST">
    <input type="text" for="Guess" name="Guess">Make your guess</input>
    <button type="submit"> Show next or submit</button>
    <button type="submit" asp-page-handler="Quit"> Quit</button>
</form>


<h2>@Model.Success</h2>

ImageGuessingGame/Pages/Lobby/JoinMultiplayer.cshtml
@page
@model JoinMultiplayerModel
@{
    ViewData["Title"] = "JoinMultiplayer";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
    }
}
<p hidden id="username">@Model.LoggedUser.UserName</p>
<h1>Wait for players before you start game</h1>
<div>
    <h4>Share this Game Id with your friends:</h4>
    <span>
        <input disabled id="gameId" value="@Model.Game.Id" />
        <button onclick="copyId()">Copy</button>
    </span>
    @if (Model.IsCreator)
    {
        <form>
            <button type="submit" id="startGame">Start Game</button>
        </form>
    }
    else
    {
        <p id="info">Waiting for host to start...</p>
    }
    <div>
        <h4>Joined players</h4>
        <ul id="playerList"></ul>
    </div>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/startgame.js"></script>
<script>
    function copyId() {
        var copyText = document.getElementById("gameId");

        copyText.select();
        copyText.setSelectionRange(0, 99999);

        navigator.clipboard.writeText(copyText.value);
    }
</script>

ImageGuessingGame/Pages/Lobby/Lobby.cshtml
@page
@model LobbyModel
@{
    ViewData["Title"] = "Lobby";
    string[] TableHeaders = new string[] {};
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
    }
}

<a class="btn btn-primary" asp-page="CreateGame" >Create Game</a> 
<a class="btn btn-primary" asp-page="Upload"> Upload Image</a>
<h2>Recent games</h2>
<table class="table  table-striped table-hover">
    <thead>
        <tr>
            <th>Game ID</th>
            <th>User</th>
            <th>Image label</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Games)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Guesser.User</td>
                <td>@item.Oracle.Label</td>
            </tr>
        }
    </tbody>
</table>

ImageGuessingGame/Pages/Lobby/Lose.cshtml
@page
@model LoseModel
@{
    ViewData["Title"] = "Lose";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<h1> You lost</h1>
<p> The label was @Model.Label</p>
<img src="../output.png" />

ImageGuessingGame/Pages/Lobby/MultiplayerGame.cshtml
@page
@model MultiplayerGameModel
@{
    ViewData["Title"] = "Multiplayer";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";

    }
}
<img id = "img" src="../output.png" />
<p hidden id="userName">@Model.LoggedUser</p>
<p hidden id="gameId">@Model.Game.Id</p>


<form method=" ">
    <label for="guess">Make your guess</label>
    <input type="text" name="guess" id="guess"></input>
    <button id ="submit"> Show next or submit</button>
</form>


<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/multiplayer.js"></script>

ImageGuessingGame/Pages/Lobby/Suggest.cshtml
@page
@model SuggestModel
@{
    ViewData["Title"] = "Suggest";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<h1> Suggest 5 pieces that would've helped you the most</h1>
<div>
    <img id="imgsuggest" src="../output.png" />
</div>
<p> You chose @if(@Model.Index != -1){
    @Model.Index
}
</p>
<form asp-page-handler="Choose" method="post">
        <button style="outline: 0;" id = "myButton"></button>
        <input id ="cursorx" type="hidden" name="cursorx" value="" />
        <input id ="cursory" type="hidden" name="cursory" value="" />
</form>
<script type="text/javascript">
function printMousePos(event) {
    document.getElementById("cursorx").value = event.offsetX;
    document.getElementById("cursory").value = event.offsetY;
    document.getElementById("myButton").click();
}
window.onload = function(){
    document.getElementById('imgsuggest').addEventListener('click', printMousePos); 
}
</script>

ImageGuessingGame/Pages/Lobby/Suggestions.cshtml
@page
@model SuggestionsModel
@{
    ViewData["Title"] = "Suggsestions";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<h1> Suggestions </h1>
<img id="image" src="../output.png">

ImageGuessingGame/Pages/Lobby/Upload.cshtml
@page
@model UploadModel
@{
    ViewData["Title"] = "Upload";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<h1>Upload an image</h1>
<img id = "user_img" height = "400"  width = "600"  style = "border:solid" />
<form method="post" enctype="multipart/form-data">
  <label asp-for="ImageFile">Select image:</label>
  <input asp-for="ImageFile" type="file"  onchange="show(this)">
  <p> Add a label for your image</p> 
  <input name="label" type="text" required>
  <input type="submit">
</form>

<script type="text/javascript">  
   function show(input) {  
      if (input.files && input.files[0]) {  
      var filerdr = new FileReader();  
      filerdr.onload = function (e) {  
         $('#user_img').attr('src', e.target.result);  
      }  
      filerdr.readAsDataURL(input.files[0]);  
      cutImageUp();
   } 
}  
</script>  

ImageGuessingGame/Pages/Lobby/Win.cshtml
@page
@model WinModel
@{
    ViewData["Title"] = "Win";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<h1> You guessed correct</h1>
<p> The label was @Model.Label</p>
<img src="../output.png" />

<h2> Your score is @Model.Score</h2>

<a class="btn btn-primary" asp-page="Suggest"> Suggest pieces for future play</a>

ImageGuessingGame/Pages/Lobby/WinMulti.cshtml
@page
@model WinMultiModel
@{
    ViewData["Title"] = "Win Multiplayer";
    if (Model.LoggedUser != null)
    {
        Layout = "_LoggedLayout";
 
    }
}
<h1> @Model.Winner IS THE WINNER</h1>
<p> The label was @Model.Label</p>
<h2> @Model.Winner got a score of: @Model.Score</h2>
<img src="../output.png" />


@{if (@Model.Winner == @Model.LoggedUser){
    <a class="btn btn-primary" asp-page="Suggest"> Suggest pieces for future play</a>
}
}